apiVersion: v1
kind: ConfigMap
metadata:
  name: my-redis-config
  namespace: gutsy
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    protected-mode no
    dir /data
    dbfilename data.rdb
    save 900 1
    save 300 10
    save 60 10000
