apiVersion: v1
kind: ConfigMap
metadata:
  name: my-redis-config
  namespace: gutsy
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    protected-mode no
    dir /data
    dbfilename dump.rdb
    save 900 1
    save 300 10
    save 60 10000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: gutsy
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
       app: redis
    spec:
      containers:
      - name: redis-container
        image: redis:7.2-alpine
        ports:
          - containerPort: 6379
        resources:
              requests:
                 cpu: "500m"
                 memory: 2G
              limits:
                cpu: "1000m"
                memory: 4G
        volumeMounts:
          - name: data-volume
            mountPath: /data
          - name: redis-config
            mountPath: /redis-master
      volumes:
      - name: redis-config
        configMap:
           name: my-redis-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: redis-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: redis-container-service
  namespace: gutsy
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP

