apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: gutsy
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
       app: redis
    spec:
      containers:
      - name: redis-container
        image: redis:7.2-alpine
        command: ["redis-server", "/redis-master/redis.conf"]
        ports:
          - containerPort: 6379
        resources:
              requests:
                 cpu: "500m"
                 memory: 2G
              limits:
                cpu: "1"
                memory: 4G
        volumeMounts:
          - name: data-volume
            mountPath: /data
          - name: redis-config
            mountPath: /redis-master
      volumes:
      - name: redis-config
        configMap:
           name: my-redis-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: redis-pvc

