
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: gutsy
  labels:
    app: gutsy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gutsy-server
  template:
    metadata:
      labels:
       app: gutsy-server
    spec:
      containers:
      - name: gutsy-server-container
        image: yidgar11/server:1.0
        ports:
          - containerPort: 9090
        resources:
              requests:
                 cpu: "500m"
                 memory: 2G
              limits:
                cpu: "1"
                memory: 4G
        volumeMounts:
          - name: data
            mountPath: /gutsy-server-master-data
      volumes:
        - name: data
          emptyDir: {}

