apiVersion: v1
kind: Service
metadata:
  name: gutsy-server-container-service
  namespace: gutsy
spec:
  selector:
    app: gutsy-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP